/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prototypes;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class COrdemProducaoGUI extends javax.swing.JFrame {
    
    
        
    //chamado de outra classe
    Metodos call = new Metodos();
    
    
    /**
     * Creates new form Gera_op
     */
    public COrdemProducaoGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catBox = new javax.swing.JComboBox<>();
        eeText = new javax.swing.JLabel();
        catText = new javax.swing.JLabel();
        largTecText = new javax.swing.JLabel();
        metTecText = new javax.swing.JLabel();
        lonText = new javax.swing.JLabel();
        obsText = new javax.swing.JLabel();
        metTecField = new javax.swing.JTextField();
        lonField = new javax.swing.JTextField();
        obsField = new javax.swing.JTextField();
        btnConfirmOP = new javax.swing.JButton();
        btnAddPedOP = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabPedidosOP = new javax.swing.JTable();
        eeBox = new javax.swing.JComboBox<>();
        boxLargTec1 = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar Ordem de Produção");

        catBox.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        catBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agrothor", "Primethor", "Agropem" }));

        eeText.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        eeText.setText("EE:");

        catText.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        catText.setText("Categoria:");

        largTecText.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        largTecText.setText("Largura Tecido:");

        metTecText.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        metTecText.setText("Metragem Tecido:");

        lonText.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lonText.setText("Lonas:");

        obsText.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        obsText.setText("Observação:");

        metTecField.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        metTecField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metTecFieldActionPerformed(evt);
            }
        });

        lonField.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lonField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lonFieldActionPerformed(evt);
            }
        });

        obsField.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        obsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obsFieldActionPerformed(evt);
            }
        });

        btnConfirmOP.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnConfirmOP.setText("Confirmar");
        btnConfirmOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmOPActionPerformed(evt);
            }
        });

        btnAddPedOP.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        btnAddPedOP.setText("Adicionar Pedido");
        btnAddPedOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPedOPActionPerformed(evt);
            }
        });

        tabPedidosOP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pedido", "Nome Cliente", "Largura Pedido", "Metragem Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabPedidosOP);
        if (tabPedidosOP.getColumnModel().getColumnCount() > 0) {
            tabPedidosOP.getColumnModel().getColumn(0).setPreferredWidth(75);
            tabPedidosOP.getColumnModel().getColumn(1).setPreferredWidth(400);
            tabPedidosOP.getColumnModel().getColumn(2).setPreferredWidth(75);
            tabPedidosOP.getColumnModel().getColumn(3).setPreferredWidth(75);
        }

        eeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90", "100", "125", "140" }));
        eeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeBoxActionPerformed(evt);
            }
        });

        boxLargTec1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16\"", "20\"", "24\"", "28\"" }));

        btnBack.setText("Voltar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catText)
                            .addComponent(catBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eeText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(largTecText)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(boxLargTec1, 0, 106, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metTecText)
                            .addComponent(metTecField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lonField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lonText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(obsText)
                                .addGap(0, 133, Short.MAX_VALUE))
                            .addComponent(obsField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddPedOP)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmOP))
                            .addComponent(btnBack))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catText)
                            .addComponent(largTecText)
                            .addComponent(metTecText)
                            .addComponent(lonText)
                            .addComponent(obsText))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metTecField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lonField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obsField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxLargTec1)
                            .addComponent(eeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(eeText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(catBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmOP)
                    .addComponent(btnAddPedOP))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void metTecFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metTecFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metTecFieldActionPerformed

    private void lonFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lonFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lonFieldActionPerformed

    private void obsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obsFieldActionPerformed

    private void btnConfirmOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmOPActionPerformed

//Convertendo as variáveis em String
    String categoriaOP = (String) catBox.getSelectedItem();
    String eeOP = (String) eeBox.getSelectedItem();
    String larguraTecido = (String) eeBox.getSelectedItem();
    String metragemTecido = metTecField.getText();
    String lonaTecido = lonField.getText();
    String OBS = obsField.getText();
    
    
    
    //if para impedir de ter alguma informação faltando
    if("".equals(eeOP) || "".equals(metragemTecido) || "".equals(lonaTecido)){
         JOptionPane.showMessageDialog(null, "Preencha todos os campos de especificações!","ERRO!",JOptionPane.WARNING_MESSAGE);
    } else {
        //switch para a confirmação do usuário
        switch(JOptionPane.showConfirmDialog(null,
                "Gostaria de gerar a seguinte Ordem de Produção?" + "\nCategoria: " + categoriaOP + "\nEE: " + eeOP + "\nLargura Tecido: " + larguraTecido + "\nMetragem Tecido: " + metragemTecido + "\nLonas: " + lonaTecido + "\nOBS: " + OBS,
                "Confirmação de Ordem de Produção",JOptionPane.YES_NO_OPTION)){
            case JOptionPane.YES_OPTION :{
                JOptionPane.showMessageDialog(null,"Ordem de Produção gerada com Sucesso!");
                dispose();//fecha a janela Gera_op
                break;
            }
        }
     
    }

    }//GEN-LAST:event_btnConfirmOPActionPerformed

    private void btnAddPedOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPedOPActionPerformed
       call.act_addPedidoOP();
    }//GEN-LAST:event_btnAddPedOPActionPerformed

    private void eeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eeBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();   
    }//GEN-LAST:event_btnBackActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxLargTec1;
    private javax.swing.JButton btnAddPedOP;
    private javax.swing.JButton btnBack;
    public javax.swing.JButton btnConfirmOP;
    private javax.swing.JComboBox<String> catBox;
    private javax.swing.JLabel catText;
    private javax.swing.JComboBox<String> eeBox;
    private javax.swing.JLabel eeText;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel largTecText;
    private javax.swing.JTextField lonField;
    private javax.swing.JLabel lonText;
    private javax.swing.JTextField metTecField;
    private javax.swing.JLabel metTecText;
    private javax.swing.JTextField obsField;
    private javax.swing.JLabel obsText;
    private javax.swing.JTable tabPedidosOP;
    // End of variables declaration//GEN-END:variables
}
