package estoque;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menus.MenuGUI;
import produtos.Produto;
import produtos.ProdutoDAO;


/**
 *
 * @author Lenovo
 */
public class CEstoqueGUI extends javax.swing.JFrame {

    /**
     * Creates new form CEstoqueGUI
     */
    public CEstoqueGUI() {
        initComponents();
        categoriaBox();
        tabela();   
    }

    
    //Adicionandos os itens da tabela de produtos a  combobox
    public void categoriaBox(){
        ProdutoDAO produtodao = new ProdutoDAO();
        
        try{
            List<Produto> produtoList = produtodao.categoriaBox(); 
                box_category.addItem(null);
            for(Produto produto : produtoList){
                box_category.addItem(produto.getProduto()); 
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        box_category.setSelectedItem(null);
        box_lona.setSelectedItem(null);
    }
    
    
    
    // Gerando itens na tabela
    public void tabela(){
        EstoqueDAO estoquedao = new EstoqueDAO();
        DefaultTableModel modelo = (DefaultTableModel) tab_estoque.getModel();
        
        ////
        //limpando tabela
        while(tab_estoque.getModel().getRowCount() > 0 ){
            ((DefaultTableModel) tab_estoque.getModel()).removeRow(0);
        }
        ////
        
        List<Estoque> estoqueList = estoquedao.selectEstoque();
        for (Estoque estoque : estoqueList) {
            //criando e adicionado rows a tabela
            Object[] line = {estoque.getId(), estoque.getCategoria(), estoque.getLonas(), estoque.getLargura(), estoque.getMetragem()};
            modelo.addRow(line);
        }
        
    }
    
    
    public void filtro(){
        // Aplicando filtro
           EstoqueDAO estoquedao = new EstoqueDAO();
           DefaultTableModel modelo = (DefaultTableModel) tab_estoque.getModel();

           ////
           //limpando a tabela
           while(tab_estoque.getModel().getRowCount() > 0 ){
               ((DefaultTableModel) tab_estoque.getModel()).removeRow(0);
           }
           ////
           
           
           String categoria = String.valueOf(box_category.getSelectedItem());
           String lonas = String.valueOf(box_lona.getSelectedItem());
           String largura = largField.getText();
           String metragem = metField.getText();
           
           if(box_category.getSelectedItem() == null){
            categoria = " ";
            
            } else {
                System.out.println(categoria);
                categoria = " categoria = '" + categoria + "' and";
            }
            //lonas
            if(box_lona.getSelectedItem() == null){

                lonas = "> 0";
            } else {
                System.out.println(lonas);
                lonas = "= " + lonas;
            }
            //largura
            if(largura.isEmpty()){
                largura = "0";
            }
            //metragem
            if(metragem.isEmpty()){
                metragem = "0";
            }
           
           
           // Função que retorna uma lista com os objetos após aplicar o filtro
           List<Estoque> estoqueList = estoquedao.buscaEstoque(categoria, lonas,largura,metragem);
           
           //Inserindo itens na tabela
           for (Estoque estoque : estoqueList) {

               Object[] line = {estoque.getId(), estoque.getCategoria(), estoque.getLonas(), estoque.getLargura(), estoque.getMetragem()};
               modelo.addRow(line);
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_estoque = new javax.swing.JTable();
        add_estoque = new javax.swing.JButton();
        upd_estoque = new javax.swing.JButton();
        del_est = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        busca_est = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        largField = new javax.swing.JTextField();
        metField = new javax.swing.JTextField();
        box_category = new javax.swing.JComboBox<>();
        box_lona = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estoque Correias");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tab_estoque.setBackground(new java.awt.Color(255, 255, 255));
        tab_estoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tab_estoque.setForeground(new java.awt.Color(0, 0, 0));
        tab_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Lonas", "Largura", "Metragem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_estoque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_estoque.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane5.setViewportView(tab_estoque);

        add_estoque.setBackground(new java.awt.Color(255, 255, 255));
        add_estoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adicionar.png"))); // NOI18N
        add_estoque.setText("Adicionar");
        add_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_estoqueActionPerformed(evt);
            }
        });

        upd_estoque.setBackground(new java.awt.Color(255, 255, 255));
        upd_estoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        upd_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar (2).png"))); // NOI18N
        upd_estoque.setText("Editar");
        upd_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_estoqueActionPerformed(evt);
            }
        });

        del_est.setBackground(new java.awt.Color(255, 255, 255));
        del_est.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        del_est.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/excluir.png"))); // NOI18N
        del_est.setText("Excluir");
        del_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_estActionPerformed(evt);
            }
        });

        btn_voltar.setBackground(new java.awt.Color(255, 255, 255));
        btn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botao-voltar (1).png"))); // NOI18N
        btn_voltar.setBorder(null);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        busca_est.setBackground(new java.awt.Color(255, 255, 255));
        busca_est.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        busca_est.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/procurar.png"))); // NOI18N
        busca_est.setText("Buscar");
        busca_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_estActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Filtros:");

        largField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largFieldActionPerformed(evt);
            }
        });

        metField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metFieldActionPerformed(evt);
            }
        });

        box_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_categoryActionPerformed(evt);
            }
        });

        box_lona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { null,"2", "3", "4", "5", "6", "8", "10" }));
        box_lona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_lonaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Categoria");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lonas");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Largura");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Metragem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_voltar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(box_category, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(box_lona, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(largField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(metField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(91, 91, 91)
                                            .addComponent(jLabel2)
                                            .addGap(93, 93, 93)
                                            .addComponent(jLabel3))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(add_estoque)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(upd_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(del_est)))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(busca_est)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(75, 75, 75)
                                            .addComponent(jLabel5)))
                                    .addGap(39, 39, 39))))
                        .addGap(0, 439, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upd_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(del_est, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(busca_est, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(largField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_lona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Adicionar item
    private void add_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_estoqueActionPerformed
        EstoqueDAO estoquedao = new EstoqueDAO();
        // Gerando JOptionPane e inserindo item a tabela
        estoquedao.insertEstoque(estoquedao.pane(null,0,null,null));
        JOptionPane.showMessageDialog(null,"Correia adicionada com sucesso!");
        tabela();
        
    }//GEN-LAST:event_add_estoqueActionPerformed
    
    //Remover item
    private void del_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_estActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = tab_estoque.getSelectedRow();
        if(linhaSelecionada >=0){
            
            //Confirmação do usuario
            switch(JOptionPane.showConfirmDialog(null,"Deseja mesmo excluir essa correia?","Aviso",JOptionPane.YES_NO_OPTION)){
                case JOptionPane.YES_OPTION:    
                EstoqueDAO estoquedao = new EstoqueDAO(); 
                int id = (int) tab_estoque.getValueAt(linhaSelecionada, 0);
                //Deletando o produto e gerando a tabela novamente
                estoquedao.deleteEstoque(id);
                tabela();
                
            break;
            }
            
        } else {
            JOptionPane.showMessageDialog(null,"Selecione a correia que deseja excluir");
        }
        
    }//GEN-LAST:event_del_estActionPerformed

    // editar item
    private void upd_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_estoqueActionPerformed
        EstoqueDAO estoquedao = new EstoqueDAO();
        
        int linhaSelecionada = -1;
        linhaSelecionada = tab_estoque.getSelectedRow();
        if(linhaSelecionada >=0){
            
            // Pegando valores da tabela
            int id = (int) tab_estoque.getValueAt(linhaSelecionada,0);
            String categoria = (String) tab_estoque.getValueAt(linhaSelecionada,1);
            int lonas = (int) Integer.valueOf( String.valueOf(tab_estoque.getValueAt(linhaSelecionada,2)));
            String largura = (String) String.valueOf(tab_estoque.getValueAt(linhaSelecionada,3));
            String metragem = (String) String.valueOf(tab_estoque.getValueAt(linhaSelecionada,4));
            
            // Gerando JOptionPane para editar a tabela
            estoquedao.updadeEstoque(estoquedao.pane(categoria, lonas, largura, metragem), id);
            tabela();
            
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a correia que deseja editar");
        }
        
        
        
        
    }//GEN-LAST:event_upd_estoqueActionPerformed
    
    // voltar
    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        MenuGUI menugui = new MenuGUI();
        menugui.setVisible(true);
        menugui.setExtendedState(MAXIMIZED_BOTH);
        dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    // filtar estoque
    private void busca_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_estActionPerformed
        filtro();
    }//GEN-LAST:event_busca_estActionPerformed

    private void box_lonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_lonaActionPerformed
        filtro();
    }//GEN-LAST:event_box_lonaActionPerformed

    private void box_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_categoryActionPerformed
        filtro();
    }//GEN-LAST:event_box_categoryActionPerformed

    private void largFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largFieldActionPerformed
        filtro();
    }//GEN-LAST:event_largFieldActionPerformed

    private void metFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metFieldActionPerformed
        filtro();
    }//GEN-LAST:event_metFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CEstoqueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_estoque;
    private javax.swing.JComboBox<String> box_category;
    private javax.swing.JComboBox<String> box_lona;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JButton busca_est;
    private javax.swing.JButton del_est;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField largField;
    private javax.swing.JTextField metField;
    private javax.swing.JTable tab_estoque;
    private javax.swing.JButton upd_estoque;
    // End of variables declaration//GEN-END:variables
}
